#' Paths to the top-level level of the administrations and/or events implemented in the model
#'
#' @include enum.R
#' @export
Events <- enum(list(
   IV_bolus = 'IV bolus',
   IC_bolus = 'IC bolus|Default',
   IC_mult_3 = 'IC multiple 3d|Default',
   IC_mult_4 = 'IC multiple 4d|Default',
   IC_mult_5 = 'IC multiple 5d|Default',
   IC_mult_14 = 'IC multiple 14d|Default',
   IC_mult_21 = 'IC multiple 21d|Default',
   IC_mult_28 = 'IC multiple 28d|Default',
   IC_mult_30 = 'IC multiple 30d|Default',
   IC_mult_33 = 'IC multiple 33d|Default',
   IC_mult_34 = 'IC multiple 34d|Default',
   IC_mult_35 = 'IC multiple 35d|Default'
))

OutputGroups <- enum(list(
  VenousBlood = "Plasma",
  Liver = 'Liver',
  Fat = "Fat",
  Kidney = "Kidney",
  Muscle = "Muscle",
  Heart = 'Heart',
  Ovary = 'Ovary',
  Brain = 'Brain',
  WholeEgg = "WholeEgg",
  Yolk = "Yolk",
  Albumen = "Albumen",
  Skin = "Skin",
  Lung = "Lung",
  BloodCells = 'BloodCells',
  WholeBlood = 'Blood'
))

OutputColours <- enum(list(
  Plasma = "#D73027",
  Liver = '#D95F02',
  Fat = "#7570B3",
  Kidney = "#E7298A",
  Muscle = "#1B9E77",
  Heart = '#E6AB02',
  Ovary = '#A6761D',
  Brain = '#666666',
  WholeEgg = "#4575B4",
  Yolk = "#74A9CF",
  Albumen = "#B2DF8A",
  Skin = "#33A02C",
  Lung = "#FB9A99",
  BloodCells = '#E31A1C',
  Blood = "#654321"
))

#' Path to the outputs generated by the model
#'
#' @include enum.R
#' @export
OutputPaths <- enum(list(
  VenousBlood = "Organism|VenousBlood|Plasma|DefaultCompound|Concentration in container",
  BloodCells = "Organism|VenousBlood|BloodCells|DefaultCompound|Concentration in container",
  WholeBlood = "Organism|VenousBlood|DefaultCompound|Whole Blood",
  Liver = "Organism|Liver|Periportal|DefaultCompound|Tissue",
  Fat = "Organism|Fat|DefaultCompound|Tissue",
  Kidney = "Organism|Kidney|DefaultCompound|Tissue",
  Skin = "Organism|Skin|DefaultCompound|Tissue",
  Lung = "Organism|Lung|DefaultCompound|Tissue",
  Muscle = "Organism|Muscle|DefaultCompound|Tissue",
  Heart = "Organism|Heart|DefaultCompound|Tissue",
  Ovary = "Organism|Ovary|DefaultCompound|Tissue",
  Brain = "Organism|Brain|DefaultCompound|Tissue",
  Egg1 = "Organism|Egg 1|DefaultCompound|Whole Egg",
  Egg2 = "Organism|Egg 2|DefaultCompound|Whole Egg",
  Egg3 = "Organism|Egg 3|DefaultCompound|Whole Egg",
  Egg4 = "Organism|Egg 4|DefaultCompound|Whole Egg",
  Egg5 = "Organism|Egg 5|DefaultCompound|Whole Egg",
  Egg6 = "Organism|Egg 6|DefaultCompound|Whole Egg",
  Egg7 = "Organism|Egg 7|DefaultCompound|Whole Egg",
  Egg8 = "Organism|Egg 8|DefaultCompound|Whole Egg",
  Egg9 = "Organism|Egg 9|DefaultCompound|Whole Egg",
  Egg1_alb = "Organism|Egg 1|Albumen|Intracellular|DefaultCompound|Concentration in container",
  Egg2_alb = "Organism|Egg 2|Albumen|Intracellular|DefaultCompound|Concentration in container",
  Egg3_alb = "Organism|Egg 3|Albumen|Intracellular|DefaultCompound|Concentration in container",
  Egg4_alb = "Organism|Egg 4|Albumen|Intracellular|DefaultCompound|Concentration in container",
  Egg5_alb = "Organism|Egg 5|Albumen|Intracellular|DefaultCompound|Concentration in container",
  Egg6_alb = "Organism|Egg 6|Albumen|Intracellular|DefaultCompound|Concentration in container",
  Egg7_alb = "Organism|Egg 7|Albumen|Intracellular|DefaultCompound|Concentration in container",
  Egg8_alb = "Organism|Egg 8|Albumen|Intracellular|DefaultCompound|Concentration in container",
  Egg9_alb = "Organism|Egg 9|Albumen|Intracellular|DefaultCompound|Concentration in container",
  Egg1_ylk = "Organism|Egg 1|Yolk|Intracellular|DefaultCompound|Concentration in container",
  Egg2_ylk = "Organism|Egg 2|Yolk|Intracellular|DefaultCompound|Concentration in container",
  Egg3_ylk = "Organism|Egg 3|Yolk|Intracellular|DefaultCompound|Concentration in container",
  Egg4_ylk = "Organism|Egg 4|Yolk|Intracellular|DefaultCompound|Concentration in container",
  Egg5_ylk = "Organism|Egg 5|Yolk|Intracellular|DefaultCompound|Concentration in container",
  Egg6_ylk = "Organism|Egg 6|Yolk|Intracellular|DefaultCompound|Concentration in container",
  Egg7_ylk = "Organism|Egg 7|Yolk|Intracellular|DefaultCompound|Concentration in container",
  Egg8_ylk = "Organism|Egg 8|Yolk|Intracellular|DefaultCompound|Concentration in container",
  Egg9_ylk = "Organism|Egg 9|Yolk|Intracellular|DefaultCompound|Concentration in container"
))

