#' Path to the outputs generated by the model
#'
#' @include enum.R
#' @export
OutputGroups <- enum(list(
  VenousBlood = "VenousBlood",
  Liver = 'Liver',
  Fat = "Fat",
  Kidney = "Kidney",
  Muscle = "Muscle",
  Heart = 'Heart',
  Ovary = 'Ovary',
  Brain = 'Brain',
  WholeEgg = "WholeEgg",
  Yolk = "Yolk",
  Albumen = "Albumen",
  Skin = "Skin",
  Lung = "Lung",
  BloodCells = 'BloodCells',
  WholeBlood = 'WholeBlood'
))

OutputColours <- enum(list(
  VenousBlood = "#D73027",
  Liver = '#D95F02',
  Fat = "#7570B3",
  Kidney = "#E7298A",
  Muscle = "#1B9E77",
  Heart = '#E6AB02',
  Ovary = '#A6761D',
  Brain = '#666666',
  WholeEgg = "#4575B4",
  Yolk = "#74A9CF",
  Albumen = "#B2DF8A",
  Skin = "#33A02C",
  Lung = "#FB9A99",
  BloodCells = '#E31A1C',
  WholeBlood = "#654321"
))